format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipArp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_ARP_COMMANDS_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '19', y: '73', id: tcpipArp}
