format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIPv4}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_IPV4_COMMANDS_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '131', y: '74', id: tcpipIPv4}
